# HVA - HTML Video Automator Config file

global:
  max_width: 640
  max_height: 480

development:
  log_file: ~/work/hva/hva.log
  ffmpeg_log_file: ~/work/hva/hva-ffmpeg.log

  launchpad: ~/work/hva/launchpad
  payload: ~/work/hva/payload
  
production:
  log_file: /var/log/hva.log
  ffmpeg_log_file: /var/log/hva-ffmpeg.log

  launchpad: /var/hva/launchpad
  payload: /var/hva/payload
  