# HVA - HTML Video Automator Config file

global:
  max_width: 640
  max_height: 480

development:
  log_file: /Users/arko/work/hva/hva.log
  ffmpeg_log_file: /Users/arko/work/hva/hva-ffmpeg.log

  dropbox: /Users/arko/work/hva/dropbox
  outbox: /Users/arko/work/hva/public
  pub_url: /Users/arko/work/hva/public

production:
  log_file: /var/log/hva.log
  ffmpeg_log_file: /var/log/hva-ffmpeg.log

  dropbox: /var/hva/dropbox
  outbox: /var/hva/outbox
  pub_url: http://podcast.unil.ch/hva
