# HVA - HTML Video Automator Config file
# All URLs or paths without trailing slash ('http://example.com/hva' or '/var/hva')

# When in production, turn this on
enable_mutex: false

# App's working directories (Relative paths to 'home' accepted)
home: ~/work/hva # Change this to where the app's root is located
dropbox: dropbox
deliverables: deliverables
public: public

# Log files (Relative paths to 'home' accepted)
log_file: log/hva.log
ffmpeg_log_file: log/ffmpeg.log

# Public access URLs
app_root_url: http://hva.dev # Serving documents from the app's 'public' directory
pub_url: http://av.unil.ch/hva # Serving documents from 'publish[path]'

# Where to publish content
publish:
  user: hva
  server: av.unil.ch
  path: /var/www/av-medias/hva

# Where to archive source files
archive:
  user: hva
  server: av.unil.ch
  path: /var/hva/sources

# Video output settings
max_width: 640
max_height: 480
